name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build JAR
        run: ./mvnw package -DskipTests=true

      - name: Deploy to Digital Ocean
        env:
          DO_API_TOKEN: ${{ DIGITAL_OCEAN_TOKEN }}
        run: |
          scp -i id_rsa.pub DRXTransportSolution-0.0.1-SNAPSHOT.jar root@104.248.128.181
          ssh -o -i id_rsa.pub user@104.248.128.181 'bash -s' < deploy-script.sh
