name: Combined Workflow

on:
  push:
    branches-ignore:
      - main
      - main-clone
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean install
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifact
          path: target/DRXTransportSolution-0.0.1-SNAPSHOT.jar
      - name: Run Unit Tests
        run: ./mvnw test
  deploy:
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-artifact
          path: target/
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Deploy
        run: |
          scp -i id_irs target/DRXTransportSolution-0.0.1-SNAPSHOT.jar root@104.248.128.181:~/scripts/
          ssh -o -i id_irs root@104.248.128.181 'bash -s' < scripts/deploy-script.sh
